### ISSUE TITLE
MTeam更新适配

### ISSUE THREAD

**Issue by UltraSoundX** [tomorrow505/auto_feed_js#107]
尊敬的作者您好：
Mteam站点最近由原架构切换到新的架构，请求适配~感谢！

**Comment by tomorrow505** [comment]
> 尊敬的作者您好： Mteam站点最近由原架构切换到新的架构，请求适配~感谢！

简单更新了下，但是有一部分还没有解决。

**Comment by Pigeva** [comment]
加油哈～大家都等着你呢

**Comment by tomorrow505** [comment]
暂且这样吧，勉强够用。
