### ISSUE TITLE
version 2.0.6.6在部分pt的种子详情页面，导致页面卡死

### ISSUE THREAD

**Issue by Suitear** [tomorrow505/auto_feed_js#118]
version      2.0.6.6

比如某个宠物站的部分种子详情页面，半天脚本就加载不出来，导致页面卡死
![image](https://github.com/tomorrow505/auto_feed_js/assets/9960618/9327e9e2-3adf-45df-9864-71604cc826ea)

点开violentmonkey的脚本设置页面，有报错：
![image](https://github.com/tomorrow505/auto_feed_js/assets/9960618/240933e6-d107-4eda-986a-d176561445b6)

**Comment by tomorrow505** [comment]
> version 2.0.6.6
> 
> 比如某个宠物站的部分种子详情页面，半天脚本就加载不出来，导致页面卡死 ![image](https://private-user-images.githubusercontent.com/9960618/327696517-9327e9e2-3adf-45df-9864-71604cc826ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDIzMzQsIm5iZiI6MTcxNDc0MjAzNCwicGF0aCI6Ii85OTYwNjE4LzMyNzY5NjUxNy05MzI3ZTllMi0zYWRmLTQ1ZGYtOTg2NC03MTYwNGNjODI2ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTMxMzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUyYTNmNGNmMWVhOTJmYTViNTQ5N2E3MzA1ODE1NDQwMzg3YjU3YjQwYTMyZDNkMjkyOTAzMjI1YTczNTRhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x4TdE-z8aVrm4gbI-Mk1owB5pQ_p60vfiZBVjdTIKEc)
> 
> 点开violentmonkey的脚本设置页面，有报错： ![image](https://private-user-images.githubusercontent.com/9960618/327697711-240933e6-d107-4eda-986a-d176561445b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDIzMzQsIm5iZiI6MTcxNDc0MjAzNCwicGF0aCI6Ii85OTYwNjE4LzMyNzY5NzcxMS0yNDA5MzNlNi1kMTA3LTRlZGEtOTg2YS1kMTc2NTYxNDQ1YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTMxMzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJkOTAzN2E4MGQxMDc2YzM1OTcwOTg3NGEwNDNkNzdhNDY3MjNkM2IxNjljYmJlNmI1NTQ5YjhhZDdlYTkxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z8WMOPvaZgwbtoZ_3pUIx_WLXKD2aTYJajuE0IpXceQ)

未能复现，关闭脚本再试试。
