### ISSUE TITLE
新人求教，按教程装完为什么好多功能都没有，比如一键签到，默认站点之类的，教程截图有，自己用的就没有了。

### ISSUE THREAD

**Issue by alexyilinzhu** [tomorrow505/auto_feed_js#120]
![image](https://github.com/tomorrow505/auto_feed_js/assets/129244134/67652b0b-9acc-420f-9349-7b58e552f22f)

**Comment by tomorrow505** [comment]
> ![image](https://private-user-images.githubusercontent.com/129244134/331471162-67652b0b-9acc-420f-9349-7b58e552f22f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjg0MjksIm5iZiI6MTcxNTkyODEyOSwicGF0aCI6Ii8xMjkyNDQxMzQvMzMxNDcxMTYyLTY3NjUyYjBiLTlhY2MtNDIwZi05MzQ5LTdiNThlNTUyZjIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNjQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDIwMjI3ZjBkMjA0NzIzNzUxMGMzNTYyNjQ2Mjk4MTk5OTQyMDU3N2Q3YjRmYWIxYTY1YTQwZGFkMmQ0OTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zCKSruOGEqNkM2EZufajF-WFjubyIShHqNVCX8vbDC0)

部署在种子详情页面。。。。。

**Comment by alexyilinzhu** [comment]
感谢大佬回复，我就是从种子详情页这边点签到过去了，就到了第一次打开输入设置站点的那个设置页，跳不到能看到签到站部署的页面
![image](https://github.com/tomorrow505/auto_feed_js/assets/129244134/1e906eb5-36b9-4b7e-bdd5-d8bb69957d48)

**Comment by tomorrow505** [comment]
> 感谢大佬回复，我就是从种子详情页这边点签到过去了，就到了第一次打开输入设置站点的那个设置页，跳不到能看到签到站部署的页面 ![image](https://private-user-images.githubusercontent.com/129244134/331498135-1e906eb5-36b9-4b7e-bdd5-d8bb69957d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzAzNjIsIm5iZiI6MTcxNTkzMDA2MiwicGF0aCI6Ii8xMjkyNDQxMzQvMzMxNDk4MTM1LTFlOTA2ZWI1LTM2YjktNGI3ZS1iZGQ1LWQ4YmI2OTk1N2Q0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNzE0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjg0NmRiMGE4Y2JiZjU4ZTdlZmMwZDcyYWFjYWQ5NDM0OTAxYWE5OTllY2M0YmNlMTI2MDg2NzEwYjdmOTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VsWKQ-Tcb034SOA_y1oxoCAha42Nnt0EeuInHyMc_hM)

我换了一个浏览器重新部署都并不能复现你描述的问题，建议重装。一旦跳出弹窗直接总是允许此域名即可。

**Comment by alexyilinzhu** [comment]
> > 感谢大佬回复，我就是从种子详情页这边点签到过去了，就到了第一次打开输入设置站点的那个设置页，跳不到能看到签到站部署的页面 ![image](https://private-user-images.githubusercontent.com/129244134/331498135-1e906eb5-36b9-4b7e-bdd5-d8bb69957d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzAzNjIsIm5iZiI6MTcxNTkzMDA2MiwicGF0aCI6Ii8xMjkyNDQxMzQvMzMxNDk4MTM1LTFlOTA2ZWI1LTM2YjktNGI3ZS1iZGQ1LWQ4YmI2OTk1N2Q0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNzE0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjg0NmRiMGE4Y2JiZjU4ZTdlZmMwZDcyYWFjYWQ5NDM0OTAxYWE5OTllY2M0YmNlMTI2MDg2NzEwYjdmOTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VsWKQ-Tcb034SOA_y1oxoCAha42Nnt0EeuInHyMc_hM)
> 
> 我换了一个浏览器重新部署都并不能复现你描述的问题，建议重装。一旦跳出弹窗直接总是允许此域名即可。

恢复出厂+删除+重装搞定了，感谢大佬！

**Comment by tomorrow505** [comment]
> > > 感谢大佬回复，我就是从种子详情页这边点签到过去了，就到了第一次打开输入设置站点的那个设置页，跳不到能看到签到站部署的页面 ![image](https://private-user-images.githubusercontent.com/129244134/331498135-1e906eb5-36b9-4b7e-bdd5-d8bb69957d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzAzNjIsIm5iZiI6MTcxNTkzMDA2MiwicGF0aCI6Ii8xMjkyNDQxMzQvMzMxNDk4MTM1LTFlOTA2ZWI1LTM2YjktNGI3ZS1iZGQ1LWQ4YmI2OTk1N2Q0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNzE0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjg0NmRiMGE4Y2JiZjU4ZTdlZmMwZDcyYWFjYWQ5NDM0OTAxYWE5OTllY2M0YmNlMTI2MDg2NzEwYjdmOTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VsWKQ-Tcb034SOA_y1oxoCAha42Nnt0EeuInHyMc_hM)
> > 
> > 
> > 我换了一个浏览器重新部署都并不能复现你描述的问题，建议重装。一旦跳出弹窗直接总是允许此域名即可。
> 
> 恢复出厂+删除+重装搞定了，感谢大佬！

没事，有时候我也不清楚实际步骤出了哪些问题，因为我都是按照自己的想法流程来的。
