### ISSUE TITLE
全新架构PT站YemaPT欢迎适配

### ISSUE THREAD

**Issue by yamapt** [tomorrow505/auto_feed_js#121]
尊敬的auto_feed_js作者，您好：
    我是YemaPT的站长，本站从2023年开始开发，于5月1号正式上线运行。由于是新架构，和np不兼容，目前还不支持auto_feed_js，站内的用户都希望能够适配自动转钟工具。因此特开一个issue，希望能和您一起共建，具体来说，我这边能够给您提供账号、接口文档，如果有需要可以给您单独提供新接口。

希望得到您的回复~

**Comment by tomorrow505** [comment]
> 尊敬的auto_feed_js作者，您好： 我是YemaPT的站长，本站从2023年开始开发，于5月1号正式上线运行。由于是新架构，和np不兼容，目前还不支持auto_feed_js，站内的用户都希望能够适配自动转钟工具。因此特开一个issue，希望能和您一起共建，具体来说，我这边能够给您提供账号、接口文档，如果有需要可以给您单独提供新接口。
> 
> 希望得到您的回复~

可以给个网址和账号进去看一下不？
用户名：tomorrow505，邮箱tomorrow50544@gmail.com

**Comment by yamapt** [comment]
> > 尊敬的auto_feed_js作者，您好： 我是YemaPT的站长，本站从2023年开始开发，于5月1号正式上线运行。由于是新架构，和np不兼容，目前还不支持auto_feed_js，站内的用户都希望能够适配自动转钟工具。因此特开一个issue，希望能和您一起共建，具体来说，我这边能够给您提供账号、接口文档，如果有需要可以给您单独提供新接口。
> > 希望得到您的回复~
> 
> 可以给个网址和账号进去看一下不？ 用户名：tomorrow505，邮箱[tomorrow50544@gmail.com](mailto:tomorrow50544@gmail.com)

已经向邮箱发送注册邀请了
