### ISSUE TITLE
無法一鍵轉種到Mteam, 會一直跳一堆紅字

### ISSUE THREAD

**Issue by peedan** [tomorrow505/auto_feed_js#123]
之前一直正常，
这几天一键转载到M-team就会不停地跳红字“当前资源类别为影劇/綜藝/HD，但是选项动态加载，如果没有勾选上，下滑手动勾选。"(這行红字会愈来愈多行)，
然后网页就卡死了，
更换浏览器问题依旧，,
麻烦明日大 @tomorrow505 帮忙解决一下，谢谢

**Comment by tomorrow505** [comment]
> 之前一直正常， 这几天一键转载到M-team就会不停地跳红字“当前资源类别为影劇/綜藝/HD，但是选项动态加载，如果没有勾选上，下滑手动勾选。"(這行红字会愈来愈多行)， 然后网页就卡死了， 更换浏览器问题依旧，, 麻烦明日大 @tomorrow505 帮忙解决一下，谢谢

已经有人反馈过了。
