### ISSUE TITLE
base64 JavaScript默认的atob btoa对中文无效

### ISSUE THREAD

**Issue by yamapt** [tomorrow505/auto_feed_js#129]
怀疑是标题中有中文引起的，测试标题中没有中文时，一切正常。

![image](https://github.com/tomorrow505/auto_feed_js/assets/168743846/b9a6fb16-2510-40f3-98bd-6ddacbb1d69f)

**Comment by tomorrow505** [comment]
> 怀疑是标题中有中文引起的，测试标题中没有中文时，一切正常。
> 
> ![image](https://private-user-images.githubusercontent.com/168743846/340352326-b9a6fb16-2510-40f3-98bd-6ddacbb1d69f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDc1NzgsIm5iZiI6MTcxODcwNzI3OCwicGF0aCI6Ii8xNjg3NDM4NDYvMzQwMzUyMzI2LWI5YTZmYjE2LTI1MTAtNDBmMy05OGJkLTZkZGFjYmIxZDY5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMDQxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzY2ZjE0NzlkZGFlNmVlZjFhZTU1N2Q4ODU2NTQ0ZTJjYjQ3ZTQzZTVlYWI3OTFmZThkYzBjY2FkYzQ5YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZNOtQO0vgO2EJvxm_YZTOdaOLX4F_hnBG0rvf0EvY3g)

汇报bug尽量还是加一个链接，我测试没有复现。
![image](https://github.com/tomorrow505/auto_feed_js/assets/32202634/55092b96-eb3f-40d2-aeef-a4135380414c)
