### ISSUE TITLE
憨憨转载无法下载种子

### ISSUE THREAD

**Issue by wangyan** [tomorrow505/auto_feed_js#131]
```
篡改猴：5.2.0
auto_feed: 2.0.7.0
chrome: 26.0.6478.115
```

1.转载无法下载种子
2.所有种子都弹窗禁转

![屏幕截图 2024-06-21 182021](https://github.com/tomorrow505/auto_feed_js/assets/382993/8d7bb607-23ce-4aad-b4ce-f3385f839905)

![屏幕截图 2024-06-21 182006](https://github.com/tomorrow505/auto_feed_js/assets/382993/2eb629c4-046e-4acb-94d2-8fa31ad08fce)

**Comment by tomorrow505** [comment]
> ```
> 篡改猴：5.2.0
> auto_feed: 2.0.7.0
> chrome: 26.0.6478.115
> ```
> 
> 1.转载无法下载种子 2.所有种子都弹窗禁转
> 
> ![屏幕截图 2024-06-21 182021](https://private-user-images.githubusercontent.com/382993/341731312-8d7bb607-23ce-4aad-b4ce-f3385f839905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzg3NzgsIm5iZiI6MTcxOTAzODQ3OCwicGF0aCI6Ii8zODI5OTMvMzQxNzMxMzEyLThkN2JiNjA3LTIzY2UtNGFhZC1iNGNlLWYzMzg1ZjgzOTkwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNjQxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmEzZWMwNjk3OTAxYjdmZWMxYTVkMWUxMWM0NTM0ZGQ5Njk0NzliMTI1MjkxOWEwYmYyZmFkYzMxYzJkNzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pQ9cZYNWHU5cLFh9BKVNngLYmp4hrwTOCAuJy_vp66k)
> 
> ![屏幕截图 2024-06-21 182006](https://private-user-images.githubusercontent.com/382993/341731550-2eb629c4-046e-4acb-94d2-8fa31ad08fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzg3NzgsIm5iZiI6MTcxOTAzODQ3OCwicGF0aCI6Ii8zODI5OTMvMzQxNzMxNTUwLTJlYjYyOWM0LTA0NmUtNGFjYi05NGQyLThmYTMxYWQwOGZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNjQxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjIxODUxMmQ0NTkxZTM0ZDYyOTg3YjgyYjIyZjFjY2RmNWZmNDY3NTYzOGExZmQzYjExYWQyNGI0ODBkYmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-fUjuFY1O2ed7g5VrJW70nnaknC-okv3XY49gTN-n8s)

请保持油猴5.1.1版本。

**Comment by tomorrow505** [comment]
给油猴开发者提了issue，现在用油猴测试版可以。https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf
