### ISSUE TITLE
转载到麒麟站点时的一些问题

### ISSUE THREAD

**Issue by treble1024clef** [tomorrow505/auto_feed_js#132]
版本：2.0.6.9
问题链接：
[链接1](https://www.hdkyl.in/details.php?id=33270)
[链接2](https://www.hdkyl.in/details.php?id=33164)
[链接3](https://www.hdkyl.in/details.php?id=33199)
[链接4](https://www.hdkyl.in/details.php?id=31273)
1.DDP/E-AC3识别成DD/AC3（链接1，2）
2.剧集完结标签和分集标签不会识别勾选（链接2）
3.TrueHD Atmos音频选择的是TrueHD（链接3）
4.WEBrip应该是属于Encode，脚本转的时候选择的是web-DL（链接4）

大佬有空可否处理一下，十分感谢

**Comment by tomorrow505** [comment]
> 版本：2.0.6.9 问题链接： [链接1](https://www.hdkyl.in/details.php?id=33270) [链接2](https://www.hdkyl.in/details.php?id=33164) [链接3](https://www.hdkyl.in/details.php?id=33199) [链接4](https://www.hdkyl.in/details.php?id=31273) 1.DDP/E-AC3识别成DD/AC3（链接1，2） 2.剧集完结标签和分集标签不会识别勾选（链接2） 3.TrueHD Atmos音频选择的是TrueHD（链接3） 4.WEBrip应该是属于Encode，脚本转的时候选择的是web-DL（链接4）
> 
> 大佬有空可否处理一下，十分感谢

后续处理吧，这个站点我吴昊。。。

**Comment by treble1024clef** [comment]
> > 版本：2.0.6.9 问题链接： [链接1](https://www.hdkyl.in/details.php?id=33270) [链接2](https://www.hdkyl.in/details.php?id=33164) [链接3](https://www.hdkyl.in/details.php?id=33199) [链接4](https://www.hdkyl.in/details.php?id=31273) 1.DDP/E-AC3识别成DD/AC3（链接1，2） 2.剧集完结标签和分集标签不会识别勾选（链接2） 3.TrueHD Atmos音频选择的是TrueHD（链接3） 4.WEBrip应该是属于Encode，脚本转的时候选择的是web-DL（链接4）
> > 大佬有空可否处理一下，十分感谢
> 
> 后续处理吧，这个站点我吴昊。。。

大佬，我是站点的管理，我看您有账号的呀.用户名tomorrow505 邮箱tomorrow50544@gmail.com

**Comment by tomorrow505** [comment]
> > > 版本：2.0.6.9 问题链接： [链接1](https://www.hdkyl.in/details.php?id=33270) [链接2](https://www.hdkyl.in/details.php?id=33164) [链接3](https://www.hdkyl.in/details.php?id=33199) [链接4](https://www.hdkyl.in/details.php?id=31273) 1.DDP/E-AC3识别成DD/AC3（链接1，2） 2.剧集完结标签和分集标签不会识别勾选（链接2） 3.TrueHD Atmos音频选择的是TrueHD（链接3） 4.WEBrip应该是属于Encode，脚本转的时候选择的是web-DL（链接4）
> > > 大佬有空可否处理一下，十分感谢
> > 
> > 
> > 后续处理吧，这个站点我吴昊。。。
> 
> 大佬，我是站点的管理，我看您有账号的呀.用户名tomorrow505 邮箱[tomorrow50544@gmail.com](mailto:tomorrow50544@gmail.com)

好吧，站点太多了，密码忘记了，重新找回了。

**Comment by treble1024clef** [comment]
幸苦大佬了

**Comment by treble1024clef** [comment]
大佬，可以适配一下麒麟站点的新域名吗？目前新域名还无法使用autofeed。适配可能有点麻烦，因为是用户专属定制的，每一个用户子域名都不一样
