### ISSUE TITLE
关于Torrentleech

### ISSUE THREAD

**Issue by hylf126** [tomorrow505/auto_feed_js#153]
该站的主站torrentleech.org被墙，直连可以有torrentleech.me,torrentleech.cc，以及tlgetin.cc，能否把这些域名加上呢？

**Comment by tomorrow505** [comment]
> 该站的主站torrentleech.org被墙，直连可以有torrentleech.me,torrentleech.cc，以及tlgetin.cc，能否把这些域名加上呢？

已经在配置页面添加了选择项，等待后续更新。
