### ISSUE TITLE
无法修改脚本设置站点，之前设置了某个站点之后该站点倒闭了，导致现在只能手动复制设置链接

### ISSUE THREAD

**Issue by CyEilo** [tomorrow505/auto_feed_js#155]
之前设置了某个站点之后该站点倒闭了，导致现在只能手动复制设置链接（https://xxx.xxx.com/usercp.php?action=personal#setting）后修改为别的站点域名才能打开设置
进入设置后找不到修改脚本设置站点的选项（wiki截图里有，但我这边没有可选项）
尝试过删除脚本重装，无效
不确定是我操作不对还是确实移除了该设置
望指教

**Comment by tomorrow505** [comment]
> 之前设置了某个站点之后该站点倒闭了，导致现在只能手动复制设置链接（[https://xxx.xxx.com/usercp.php?action=personal#setting）后修改为别的站点域名才能打开设置](https://xxx.xxx.com/usercp.php?action=personal#setting%EF%BC%89%E5%90%8E%E4%BF%AE%E6%94%B9%E4%B8%BA%E5%88%AB%E7%9A%84%E7%AB%99%E7%82%B9%E5%9F%9F%E5%90%8D%E6%89%8D%E8%83%BD%E6%89%93%E5%BC%80%E8%AE%BE%E7%BD%AE) 进入设置后找不到修改脚本设置站点的选项（wiki截图里有，但我这边没有可选项） 尝试过删除脚本重装，无效 不确定是我操作不对还是确实移除了该设置 望指教

![image](https://github.com/user-attachments/assets/bd73dd87-51a8-47ec-beb4-fa8025c3b83c)
就是因为定义的站点很多人没有，就直接放到种子页面了。填写内容可以参考常见问题。
