### ISSUE TITLE
之前自己手动添加站点，怎么去除？

### ISSUE THREAD

**Issue by GZCstyle** [tomorrow505/auto_feed_js#21]
之前因为有新站点不支持，我手动添加进了default_site_info，最近的更新又支持了这个站点。
但是种子页仍然能够看到2个网站简写（一个我之前自己加的，一个是作者的简写），重装、卸载重装，都仍能看到之前的简写并可点击进行转种，我在default_site_info找了下，其实我之前自己编辑进去的已经没有了，请问是要清哪里的缓存吗？

**Comment by tomorrow505** [comment]
> 之前因为有新站点不支持，我手动添加进了default_site_info，最近的更新又支持了这个站点。 但是种子页仍然能够看到2个网站简写（一个我之前自己加的，一个是作者的简写），重装、卸载重装，都仍能看到之前的简写并可点击进行转种，我在default_site_info找了下，其实我之前自己编辑进去的已经没有了，请问是要清哪里的缓存吗？

具体看这里：一个是site_order，一个是used_site_info，多余的去掉了就好了。

https://github.com/tomorrow505/auto_feed_js/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#7-%E5%A6%82%E4%BD%95%E6%8A%8A%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%AF%BC%E5%87%BA%E5%AF%BC%E5%85%A5
