### ISSUE TITLE
点击常用站点批量转种时只打开第一个

### ISSUE THREAD

**Issue by iceyuamao0510** [tomorrow505/auto_feed_js#29]
点击常用站点批量转种时只打开第一个

我记得之前时勾选了几个常用站就打开几个的

**Comment by tomorrow505** [comment]
> 点击常用站点批量转种时只打开第一个
> 
> 我记得之前时勾选了几个常用站就打开几个的

我这里没问题，你看看是不是弹窗拦截了：https://github.com/tomorrow505/auto_feed_js/wiki/%E8%AE%BE%E7%BD%AE%E9%A1%B5%E9%9D%A2

**Comment by iceyuamao0510** [comment]
果然是，而且没提醒，
