### ISSUE TITLE
我想吧其他站的种子转到我自己站怎么办呢

### ISSUE THREAD

**Issue by zzfree2021** [tomorrow505/auto_feed_js#38]
我的站点是[NexusPHP]，https://www.biho.xyz，
需要把其他站点的种子和简介转到我的站点，怎么办呢，可以自定义站点吗

**Comment by tomorrow505** [comment]
> 我的站点是[NexusPHP]，[https://www.biho.xyz，需要把其他站点的种子和简介转到我的站点，怎么办呢，可以自定义站点吗](https://www.biho.xyz%EF%BC%8C%E9%9C%80%E8%A6%81%E6%8A%8A%E5%85%B6%E4%BB%96%E7%AB%99%E7%82%B9%E7%9A%84%E7%A7%8D%E5%AD%90%E5%92%8C%E7%AE%80%E4%BB%8B%E8%BD%AC%E5%88%B0%E6%88%91%E7%9A%84%E7%AB%99%E7%82%B9%EF%BC%8C%E6%80%8E%E4%B9%88%E5%8A%9E%E5%91%A2%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9%E5%90%97)

详情见常见问题。
