### ISSUE TITLE
GZ音乐站快速搜索

### ISSUE THREAD

**Issue by evafans** [tomorrow505/auto_feed_js#40]
不知道能不能在快速搜索里增加：RED OPS DIC
理由：快速搜索可以方便找到其他站没有的种，方便转种；
           可以方便换其他经济更好的站来下相同的种子

**Comment by tomorrow505** [comment]
> 不知道能不能在快速搜索里增加：RED OPS DIC 理由：快速搜索可以方便找到其他站没有的种，方便转种； 可以方便换其他经济更好的站来下相同的种子

快速搜索这部分可以自定义的，具体可以看本库wiki使用教程。
