### ISSUE TITLE
"脚本设置" 始终跳转到 sharkpt，跳转之后页面展示异常

### ISSUE THREAD

**Issue by KrabsWong** [tomorrow505/auto_feed_js#41]
安装了最新版本的 auto_feed 插件。

在种子详情页面点击“脚本设置”，会跳转到个人设置页面（URL中增加了 `#settings` 这个 hash）

但是页面展示错误 - 破页了，同时在控制台可以看到报错信息

另外一个问题是，“脚本设置” 始终会跳转到 sharkpt 的地址？是不是我的设置有问题？

相关截图如下

### 在 HDTime 站操作

> 脚本设置依然是指向了 sharkpt

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/12368943/214202222-e554e470-4f6c-4ade-8c4d-648733fa9308.png">

进入个人设置页面之后，页面展示以及控制台内容如下

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/12368943/214202466-3263a7c0-0e52-441f-9eb2-bd3ed5cb4dad.png">

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/12368943/214202089-80ef911a-d9ab-4aff-996b-c50042ff2dab.png">

**Comment by tomorrow505** [comment]
> 安装了最新版本的 auto_feed 插件。
> 
> 在种子详情页面点击“脚本设置”，会跳转到个人设置页面（URL中增加了 `#settings` 这个 hash）
> 
> 但是页面展示错误 - 破页了，同时在控制台可以看到报错信息
> 
> 另外一个问题是，“脚本设置” 始终会跳转到 sharkpt 的地址？是不是我的设置有问题？
> 
> 相关截图如下
> 
> ### 在 HDTime 站操作
> > 脚本设置依然是指向了 sharkpt
> 
> <img alt="image" width="1283" src="https://user-images.githubusercontent.com/12368943/214202222-e554e470-4f6c-4ade-8c4d-648733fa9308.png">
> 
> 进入个人设置页面之后，页面展示以及控制台内容如下
> 
> <img alt="image" width="1482" src="https://user-images.githubusercontent.com/12368943/214202466-3263a7c0-0e52-441f-9eb2-bd3ed5cb4dad.png">
> 
> <img alt="image" width="1356" src="https://user-images.githubusercontent.com/12368943/214202089-80ef911a-d9ab-4aff-996b-c50042ff2dab.png">

参见常见问题。
