### ISSUE TITLE
大佬，申请是否能支持一下exoticaz站转到馒头的场景

### ISSUE THREAD

**Issue by weige3061** [tomorrow505/auto_feed_js#5]
大佬，申请是否能支持一下exoticaz站转到馒头的场景

**Comment by weige3061** [comment]
补充一下，能支持互转更好，感谢感谢

**Comment by weige3061** [comment]
补充一下，能支持互转更好，感谢感谢

**Comment by tomorrow505** [comment]
> 大佬，申请是否能支持一下exoticaz站转到馒头的场景

额，我没有这个站。。这个业务场景还是算了吧:sweat_smile:~~

**Comment by weige3061** [comment]
是否介意我邀请你一下😅，这个站和AZ还有PHD都是一个联盟的，所有的规则和网站模板样式都是通用的，因为EXO的资源比较新，有些时候想搬运到馒头一些，如果工具支持就很棒，大佬如果碍于大姐姐站的特殊性可能会给工具带来不好影响的话就算了，如果不是就考虑下 我邀请你入站，前两天这个站还开注来着，今天我试了下关闭了，不过我可以马上邀请你，再次感谢大佬。

**Comment by tomorrow505** [comment]
> 是否介意我邀请你一下😅，这个站和AZ还有PHD都是一个联盟的，所有的规则和网站模板样式都是通用的，因为EXO的资源比较新，有些时候想搬运到馒头一些，如果工具支持就很棒，大佬如果碍于大姐姐站的特殊性可能会给工具带来不好影响的话就算了，如果不是就考虑下 我邀请你入站，前两天这个站还开注来着，今天我试了下关闭了，不过我可以马上邀请你，再次感谢大佬。

之前有过账号，但是很久没进去挂球了。。如果是一个联盟的支持应该不难。。。只是感觉怪怪的~~

**Comment by weige3061** [comment]
那大佬你如果愿意让我邀请你入站的话，就劳烦你用自己可以用的邮箱给我的邮箱发一封邮件，我会按照你来信邮箱邀请你入站的，我把我的邮箱留在你这里262979345@qq.com，辛苦感谢。。。
