### ISSUE TITLE
favicon 性能优化建议

### ISSUE THREAD

**Issue by wen-long** [tomorrow505/auto_feed_js#50]
现在加载不同站点 icon 会发起多个连接，多少影响性能
建议使用 base64 预存站点 icon，省掉网络访问
或者使用图片缓存 CDN 如 https://images.weserv.nl 减少请求数量

例如使用 https://wsrv.nl/?url=https://pt.2xfree.org/favicon.ico
可查看图片
![](https://wsrv.nl/?url=https://pt.2xfree.org/favicon.ico)

**Comment by tomorrow505** [comment]
> 图片缓存 CDN

你要是有时间可以帮忙弄一下呗，提交一个PR。最近实在是没时间~~
