### ISSUE TITLE
照虎画猫，添加了BITPT极速之星作为转发站

### ISSUE THREAD

**Issue by Easy0Fame** [tomorrow505/auto_feed_js#6]
虽然能用但是很多bug，暂时还不会调，大佬能帮忙看下吗？
[auto_feed.user_2104182205_EasyFame.txt](https://github.com/tomorrow505/auto_feed_js/files/6392480/auto_feed.user_2104182205_EasyFame.txt)

**Comment by tomorrow505** [comment]
> 虽然能用但是很多bug，暂时还不会调，大佬能帮忙看下吗？
> [auto_feed.user_2104182205_EasyFame.txt](https://github.com/tomorrow505/auto_feed_js/files/6392480/auto_feed.user_2104182205_EasyFame.txt)

这个站我没有，你可以邀请不？我是教育网但是注册不了，虽然进去了大概率酱油。

**Comment by Easy0Fame** [comment]
> > 虽然能用但是很多bug，暂时还不会调，大佬能帮忙看下吗？
> > [auto_feed.user_2104182205_EasyFame.txt](https://github.com/tomorrow505/auto_feed_js/files/6392480/auto_feed.user_2104182205_EasyFame.txt)
> 
> 这个站我没有，你可以邀请不？我是教育网但是注册不了，虽然进去了大概率酱油。

没有权限。蒲公英高校邀请区倒是有发药的。。。
