### ISSUE TITLE
jpop转ops部分失效

### ISSUE THREAD

**Issue by Marblebishop** [tomorrow505/auto_feed_js#61]
已知缺少的有
1. 图片是thumb nail，非正常尺寸的原图
2. artists
3. bitrate
4. tag
5. description img不被需要
6. release type
感谢大佬

**Comment by tomorrow505** [comment]
> 已知缺少的有
> 
> 1. 图片是thumb nail，非正常尺寸的原图
> 2. artists
> 3. bitrate
> 4. tag
> 5. description img不被需要
> 6. release type
>    感谢大佬

因为jpop跟其他GZ框架音乐站不一样，没法直接生成json，需要主动获取，所以适配的时候并没有过多支持这一部分。虽然我这里做了一些处理，但是实在要转，建议结合YADG自己再花点功夫。

**Comment by Marblebishop** [comment]
> > 已知缺少的有
> > 
> > 1. 图片是thumb nail，非正常尺寸的原图
> > 2. artists
> > 3. bitrate
> > 4. tag
> > 5. description img不被需要
> > 6. release type
> >    感谢大佬
> 
> 因为jpop跟其他GZ框架音乐站不一样，没法直接生成json，需要主动获取，所以适配的时候并没有过多支持这一部分。虽然我这里做了一些处理，但是实在要转，建议结合YADG自己再花点功夫。

能否请大佬指点一下想要适配的话应该修改那一部分呢？大概如何主动获取？

9072行如果把cover改为空（‘’）会直接使tracklist也不生成，请问这是什么原因呢？

**Comment by tomorrow505** [comment]
> > > 已知缺少的有
> > > 
> > > 1. 图片是thumb nail，非正常尺寸的原图
> > > 2. artists
> > > 3. bitrate
> > > 4. tag
> > > 5. description img不被需要
> > > 6. release type
> > >    感谢大佬
> > 
> > 
> > 因为jpop跟其他GZ框架音乐站不一样，没法直接生成json，需要主动获取，所以适配的时候并没有过多支持这一部分。虽然我这里做了一些处理，但是实在要转，建议结合YADG自己再花点功夫。
> 
> 能否请大佬指点一下想要适配的话应该修改那一部分呢？大概如何主动获取？
> 
> 9072行如果把cover改为空（‘’）会直接使tracklist也不生成，请问这是什么原因呢？

有的信息我基本已经获取了，比如artist，tags这些不是一个体系，需要自己去辨别，cover我已经处理了啊。

**Comment by Marblebishop** [comment]
> 

找到了，原来是还没有发布，要手动复制粘贴过去。感谢大佬。

大佬好像把tag也修复了，简单试了几个好像tag都没问题。想问问如果再改artist和bitrate的话，大佬能否给一些简单提示？我目前正在填鸭速成js，如果能修改成功也愿意把结果发到这里来造福其他人😂

**Comment by tomorrow505** [comment]
> 佬好像把tag也修复了，简单试了几个好像tag都没问题。想问问如果再改artist和bitrat

我一般是不定时修复bug，然后统一周末推送到greasyfork。这两个作者的话我填了一个，如果想要填很多就需要借助YADG，bitrate我也简单适配了lossless的。你可以提供有问题的链接以及截图说明，比如你想要达到的效果，现有的问题等等。

**Comment by Marblebishop** [comment]
https://jpopsuki.eu/torrents.php?id=602&torrentid=733
我看的好像都是有损bitrate留空了。

有些种子在YADG上也找不到，但是artist在jpop上面写的很详细。请问有什么办法能从直接站点本身获取吗？这个和大佬修复的tag是一个原理吗？

上面漏了一条，还有一个需要修改的是[quote=tracklist]，我在转种时被一个非管理Ultimate TM指正description非必要不quote。可以参考这里的格式：https://orpheus.network/forums.php?action=viewthread&threadid=1859

**Comment by Marblebishop** [comment]
还有就是转有些种子的时候没有自动填充种子文件
https://jpopsuki.eu/torrents.php?id=520&torrentid=10149
但相同种子的无损格式没有出现问题，虽然名称并不相同
https://jpopsuki.eu/torrents.php?id=520&torrentid=3815

**Comment by tomorrow505** [comment]
> 还有就是转有些种子的时候没有自动填充种子文件 https://jpopsuki.eu/torrents.php?id=520&torrentid=10149 但相同种子的无损格式没有出现问题，虽然名称并不相同 https://jpopsuki.eu/torrents.php?id=520&torrentid=3815

已经修复，可以试试。
