### ISSUE TITLE
从OPS往外转出现错误

### ISSUE THREAD

**Issue by Marblebishop** [tomorrow505/auto_feed_js#62]
感谢大佬之前的更新，目前测试正常。之前想回复发现issue已经关了就想着别再打开添麻烦了...

新的问题，ops往外转的时候会自动跳转到discogs或者其他网站。例子：
https://orpheus.network/torrents.php?id=1040514&torrentid=2212739#torrent2212739

![image](https://github.com/tomorrow505/auto_feed_js/assets/22914422/1164a5d6-13ba-4855-833a-b675e9672176)

跳转链接：
https://www.discogs.com/release/26616734-Moskow-Stay-With-Me%5Dhttps://www.discogs.com/release/26616734-Moskow-Stay-With-Me%5B/url%5D

**Comment by tomorrow505** [comment]
> 感谢大佬之前的更新，目前测试正常。之前想回复发现issue已经关了就想着别再打开添麻烦了...
> 
> 新的问题，ops往外转的时候会自动跳转到discogs或者其他网站。例子： https://orpheus.network/torrents.php?id=1040514&torrentid=2212739#torrent2212739
> 
> ![image](https://user-images.githubusercontent.com/22914422/247567805-1164a5d6-13ba-4855-833a-b675e9672176.png)
> 
> 跳转链接： https://www.discogs.com/release/26616734-Moskow-Stay-With-Me%5Dhttps://www.discogs.com/release/26616734-Moskow-Stay-With-Me%5B/url%5D

我这里一切正常，你要不加一下TG群然后方便直接交流，也可以有时候问问群友有没有相同的情况。
