### ISSUE TITLE
PTGen失效，建议更换为R大的

### ISSUE THREAD

**Issue by moerfutin** [tomorrow505/auto_feed_js#7]
一直跳这个提示
![image](https://user-images.githubusercontent.com/9960618/120613014-62f8c900-c488-11eb-9b43-ece8531e85df.png)

目前可用的是 https://api.rhilip.info/ptgen.html

感谢~

**Comment by tomorrow505** [comment]
> 一直跳这个提示
> ![image](https://user-images.githubusercontent.com/9960618/120613014-62f8c900-c488-11eb-9b43-ece8531e85df.png)
> 
> 目前可用的是 https://api.rhilip.info/ptgen.html
> 
> 感谢~

我这里好像没问题，你可以提供链接吗？

**Comment by moerfutin** [comment]
![image](https://user-images.githubusercontent.com/9960618/120950268-07c12200-c779-11eb-9f83-e5999adacfc9.png)
我试了， chrome浏览器，无论挂不挂SS，都提示上图。

同台电脑，edge浏览器，不挂SS，可以查询。

#不知道发生了什么奇怪的事情

**Comment by tomorrow505** [comment]
> ![image](https://user-images.githubusercontent.com/9960618/120950268-07c12200-c779-11eb-9f83-e5999adacfc9.png)
> 我试了， chrome浏览器，无论挂不挂SS，都提示上图。
> 
> 同台电脑，edge浏览器，不挂SS，可以查询。
> 
> #不知道发生了什么奇怪的事情

我问了其他的人，好像没有这个问题。后续看情况吧，其实内核都是一样的，我有空可以换一换。
