### ISSUE TITLE
请求适配憨憨新ui

### ISSUE THREAD

**Issue by memorycan** [tomorrow505/auto_feed_js#76]
憨憨更新新ui 无法使用一键转种

**Comment by tomorrow505** [comment]
> 憨憨更新新ui 无法使用一键转种

已经适配了啊，是不是没有更新？最新为2.0.3.6版本。

**Comment by zc16607** [comment]
> 憨憨更新新ui 无法使用一键转种

可以求邀吗，馒头id 287562 昵称 dvf123
