### ISSUE TITLE
与翻译插件 kiss-translator 冲突导致无法使用翻译

### ISSUE THREAD

**Issue by leic4u** [tomorrow505/auto_feed_js#78]
![image](https://github.com/tomorrow505/auto_feed_js/assets/32786903/a8d6d702-a971-4e1e-a769-95754d585eb4)

已经提了 issue 给 kiss-translator 项目，作者说需要这边修复。请明大看看，能否尽量解决下？

**Comment by tomorrow505** [comment]
> ![image](https://user-images.githubusercontent.com/32786903/265876185-a8d6d702-a971-4e1e-a769-95754d585eb4.png)
> 
> 已经提了 issue 给 kiss-translator 项目，作者说需要这边修复。请明大看看，能否尽量解决下？

看了一下，一是对转种影响不大，然后对方的代码不是很好阅读，会花费过多时间去解读，就不修了。
