### ISSUE TITLE
注释部分站点后其余站点也无法使用了

### ISSUE THREAD

**Issue by zhangyunwu** [tomorrow505/auto_feed_js#8]
注释掉 default_site_info 里的部分条目后，在种子页面外观正常，只显示了未被注释的那部分站点，但是这些站点图标就没有和相应的url关联，无法使用。
![image](https://user-images.githubusercontent.com/64191548/124877102-56264280-dffd-11eb-9dab-92edbad739e2.png)

期望回复。

**Comment by tomorrow505** [comment]
> 注释掉 default_site_info 里的部分条目后，在种子页面外观正常，只显示了未被注释的那部分站点，但是这些站点图标就没有和相应的url关联，无法使用。
> ![image](https://user-images.githubusercontent.com/64191548/124877102-56264280-dffd-11eb-9dab-92edbad739e2.png)
> 
> 期望回复。

1.7以后的版本需要使用新的教程，在脚本设置页面进行设置。具体见博客。
