### ISSUE TITLE
脚本在P丅P的Grid这个Stylesheet下，某些地方难以辨识

### ISSUE THREAD

**Issue by moerfutin** [tomorrow505/auto_feed_js#9]
如下图

![image](https://user-images.githubusercontent.com/9960618/126469942-b01dd0be-b345-40af-b38d-9731378cdb57.png)

![image](https://user-images.githubusercontent.com/9960618/126470356-a5e551c9-0edb-410d-ac2b-0266b9c900a6.png)

不知道有没有可能修复一下？

感谢！

**Comment by tomorrow505** [comment]
因为字体颜色选取问题吧。。因为目前来说自己使用的默认的暗色系列的，要适配所有css颜色会比较麻烦，后期有可能的话会调整吧，但是意愿不是很强。。慢慢等吧，或许哪天就自定义了。
